import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
decorations = "None"
opacity = 0.75
padding.x = 0
padding.y = 0
dynamic_title= true
startup_mode= "Windowed"
decorations_theme_variant = "Dark"

dynamic_padding = true

[font]
normal.family = "Iosevka Nerd Font"
normal.style = "Medium"

bold.family = "Iosevka Nerd Font"
bold.style = "Bold"
italic.family = "Iosevka Nerd Font"
italic.style = "Italic"

bold_italic.family = "Iosevka Nerd Font"
bold_italic.style = "Bold Italic"

size = 18.0

offset.x = 1
offset.y = 10
glyph_offset.x = 0
glyph_offset.y = 0

[cursor]
style.blinking = "always"

[terminal]
osc52 = "CopyPaste"

[colors]
transparent_background_colors = true
