general.import = ["./tokyo-night.toml", "./alacritty.window.toml"]

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 16.0
normal =  {family = "JetBrainsMono Nerd Font", style="SemiBold"}
bold = {family = "JetBrainsMono Nerd Font", style="ExtraBold"}
italic = {family = "JetBrainsMono Nerd Font", style="SemiBoldItalic"}
bold_italic = {family = "JetBrainsMono Nerd Font", style="ExtraBoldItalic"}
offset = {x = 0, y = 0}

[cursor.style]
# shape = "Underline"
blinking = "Always"

[cursor]
blink_interval = 400
unfocused_hollow = false


