#!/bin/bash

options=(
	style=round
	hidpi=on
	borders
	"active_color=gradient(top_left=0xff7aa2f7,bottom_right=0xffc6a0f6)"       # blue to purple
	"inactive_color=gradient(top_left=0xaa444b6a,bottom_right=0xaa1a1b26)"     # muted indigo to dark background
	width=6
)

borders "${options[@]}"

