separator=""
separator_color="red"
key_color="yellow"
prefer_small_ascii = false

padding = 0


[palette]
type="Light"
visible=true
glyph=" 󰄛  "

[box]
title=" Pouiiro "
border="thick"
visible=true


[custom_ascii]
color="green"
path="~/.config/macchina/themes/pouiiro.txt"



[bar]
glyph="󰄛"
hide_delimiters=true
visible=true

[randomize]
key_color=false
separator_color=false


[keys]
host="Owner"
terminal="Terminal"
disk_space = "Disk Space"
cpu="CPU"
cpu_load="CPU load"
memory="RAM"
battery="Battery"
