return {}
-- return {
--   'akinsho/bufferline.nvim',
--   event = 'VeryLazy',
--   version = '*',
--   dependencies = 'nvim-tree/nvim-web-devicons',
--   config = function()
--     require('bufferline').setup {
--       options = {
--         themable = true,
--         indicator = {
--           icon = '',
--           style = 'none',
--         },
--         diagnostics = 'nvim_lsp',
--         separator_style = 'slope',
--         separator = 'slope',
--         offsets = {
--           {
--             filetype = 'NvimTree',
--             text = 'Files Tree',
--             highlight = 'Directory',
--             separator = true,
--           },
--         },
--         custom_areas = {
--           right = function()
--             local result = {}
--             local time = os.date '%I:%M%p'
--
--             table.insert(result, { text = time .. ' 󰄛 ', fg = '#5fdfae', bold = true })
--
--             return result
--           end,
--         },
--       },
--       highlights = {
--         fill = {
--           fg = '#000000',
--           bg = '#000000',
--         },
--         separator_selected = {
--           fg = '#000000',
--         },
--         separator = {
--           fg = '#000000',
--         },
--         separator_visible = {
--           fg = '#000000',
--         },
--       },
--     }
--   end,
-- }
--
-- return {
--   'akinsho/bufferline.nvim',
--   event = 'VeryLazy',
--   version = '*',
--   dependencies = 'nvim-tree/nvim-web-devicons',
--   config = function()
--     require('bufferline').setup {
--       options = {
--         mode = 'buffers',
--         style_preset = require('bufferline').style_preset.minimal,
--         themable = true,
--         indicator = {
--           icon = '▎',
--           style = 'icon',
--         },
--         buffer_close_icon = '󰅖',
--         modified_icon = '●',
--         close_icon = '',
--         left_trunc_marker = '',
--         right_trunc_marker = '',
--         diagnostics = 'nvim_lsp',
--         diagnostics_indicator = function(count, level, diagnostics_dict, context)
--           local icon = level:match 'error' and ' ' or ' '
--           return ' ' .. icon .. count
--         end,
--         separator_style = 'thin',
--         offsets = {
--           {
--             filetype = 'NvimTree',
--             text = 'Files Tree',
--             highlight = 'Directory',
--             separator = true,
--           },
--         },
--         color_icons = true,
--         show_buffer_icons = true,
--         show_buffer_close_icons = true,
--         show_close_icon = true,
--         show_tab_indicators = true,
--         always_show_bufferline = true,
--         hover = {
--           enabled = true,
--           delay = 200,
--           reveal = { 'close' },
--         },
--         custom_areas = {
--           right = function()
--             local result = {}
--             local seve = vim.diagnostic.severity
--             local error = #vim.diagnostic.get(0, { severity = seve.ERROR })
--             local warning = #vim.diagnostic.get(0, { severity = seve.WARN })
--             if error ~= 0 then
--               table.insert(result, { text = '  ' .. error, link = 'DiagnosticError' })
--             end
--             if warning ~= 0 then
--               table.insert(result, { text = '  ' .. warning, link = 'DiagnosticWarn' })
--             end
--             return result
--           end,
--         },
--       },
--       highlights = {
--         fill = { fg = '#888888', bg = 'NONE' },
--         background = { fg = '#888888', bg = 'NONE' },
--         tab = { fg = '#888888', bg = 'NONE' },
--         tab_selected = { fg = '#ffffff', bg = 'NONE', bold = true },
--         tab_separator = { fg = '#444444', bg = 'NONE' },
--         tab_separator_selected = { fg = '#ffffff', bg = 'NONE' },
--         tab_close = { fg = '#888888', bg = 'NONE' },
--         close_button = { fg = '#888888', bg = 'NONE' },
--         close_button_visible = { fg = '#888888', bg = 'NONE' },
--         close_button_selected = { fg = '#ffffff', bg = 'NONE' },
--         buffer_visible = { fg = '#888888', bg = 'NONE' },
--         buffer_selected = { fg = '#ffffff', bg = 'NONE', bold = true, italic = true },
--         numbers = { fg = '#888888', bg = 'NONE' },
--         numbers_visible = { fg = '#888888', bg = 'NONE' },
--         numbers_selected = { fg = '#ffffff', bg = 'NONE', bold = true, italic = true },
--         diagnostic = { fg = '#ff5370', bg = 'NONE' },
--         diagnostic_visible = { fg = '#ff5370', bg = 'NONE' },
--         diagnostic_selected = { fg = '#ff5370', bg = 'NONE', bold = true, italic = true },
--         hint = { fg = '#c3e88d', bg = 'NONE' },
--         hint_visible = { fg = '#c3e88d', bg = 'NONE' },
--         hint_selected = { fg = '#c3e88d', bg = 'NONE', bold = true, italic = true },
--         hint_diagnostic = { fg = '#c3e88d', bg = 'NONE' },
--         hint_diagnostic_visible = { fg = '#c3e88d', bg = 'NONE' },
--         hint_diagnostic_selected = { fg = '#c3e88d', bg = 'NONE', bold = true, italic = true },
--         info = { fg = '#82aaff', bg = 'NONE' },
--         info_visible = { fg = '#82aaff', bg = 'NONE' },
--         info_selected = { fg = '#82aaff', bg = 'NONE', bold = true, italic = true },
--         info_diagnostic = { fg = '#82aaff', bg = 'NONE' },
--         info_diagnostic_visible = { fg = '#82aaff', bg = 'NONE' },
--         info_diagnostic_selected = { fg = '#82aaff', bg = 'NONE', bold = true, italic = true },
--         warning = { fg = '#ffcb6b', bg = 'NONE' },
--         warning_visible = { fg = '#ffcb6b', bg = 'NONE' },
--         warning_selected = { fg = '#ffcb6b', bg = 'NONE', bold = true, italic = true },
--         warning_diagnostic = { fg = '#ffcb6b', bg = 'NONE' },
--         warning_diagnostic_visible = { fg = '#ffcb6b', bg = 'NONE' },
--         warning_diagnostic_selected = { fg = '#ffcb6b', bg = 'NONE', bold = true, italic = true },
--         error = { fg = '#ff5370', bg = 'NONE' },
--         error_visible = { fg = '#ff5370', bg = 'NONE' },
--         error_selected = { fg = '#ff5370', bg = 'NONE', bold = true, italic = true },
--         error_diagnostic = { fg = '#ff5370', bg = 'NONE' },
--         error_diagnostic_visible = { fg = '#ff5370', bg = 'NONE' },
--         error_diagnostic_selected = { fg = '#ff5370', bg = 'NONE', bold = true, italic = true },
--         modified = { fg = '#e5c07b', bg = 'NONE' },
--         modified_visible = { fg = '#e5c07b', bg = 'NONE' },
--         modified_selected = { fg = '#e5c07b', bg = 'NONE' },
--         duplicate_selected = { fg = '#ffffff', bg = 'NONE', italic = true },
--         duplicate_visible = { fg = '#888888', bg = 'NONE', italic = true },
--         duplicate = { fg = '#888888', bg = 'NONE', italic = true },
--         separator_selected = { fg = '#ffffff', bg = 'NONE' },
--         separator_visible = { fg = '#444444', bg = 'NONE' },
--         separator = { fg = '#444444', bg = 'NONE' },
--         indicator_visible = { fg = '#ffffff', bg = 'NONE' },
--         indicator_selected = { fg = '#ffffff', bg = 'NONE' },
--         pick_selected = { fg = '#ffffff', bg = 'NONE', bold = true, italic = true },
--         pick_visible = { fg = '#888888', bg = 'NONE', bold = true, italic = true },
--         pick = { fg = '#888888', bg = 'NONE', bold = true, italic = true },
--         offset_separator = { fg = '#444444', bg = 'NONE' },
--         trunc_marker = { fg = '#888888', bg = 'NONE' },
--       },
--     }
--   end,
-- }
