return {}
-- return {
--   'olimorris/codecompanion.nvim',
--   lazy = false,
--   enabled = false,
--
--   dependencies = {
--     'nvim-lua/plenary.nvim',
--     'nvim-treesitter/nvim-treesitter',
--     'franco-ruggeri/codecompanion-spinner.nvim',
--   },
--   opts = {
--     strategies = {
--       chat = {
--         adapter = 'copilot',
--         model = 'claude-sonnet-4',
--         opts = {
--           completion_provider = 'cmp', -- blink|cmp|coc|default
--         },
--       },
--       inline = {
--         adapter = 'copilot',
--         model = 'claude-sonnet-4',
--       },
--       cmd = {
--         adapter = 'copilot',
--         model = 'claude-sonnet-4',
--       },
--     },
--     extensions = {
--       spinner = {},
--     },
--     log_level = 'DEBUG',
--   },
-- }
