return {
  -- {
  --   'nvzone/showkeys',
  --   cmd = 'ShowkeysToggle',
  --   laze = false,
  --   opts = {
  --     timeout = 1,
  --     maxkeys = 5,
  --     winopts = {
  --       focusable = false,
  --       relative = 'editor',
  --       style = 'minimal',
  --       border = 'rounded',
  --       height = 1,
  --       row = 0,
  --       col = 0,
  --       zindex = 100,
  --     },
  --     winhl = 'FloatBorder:Comment,Normal:Normal',
  --   },
  -- },
}
