frame = "transparent"
idle = true
maximized = false
no-multigrid = true
srgb = false
tabs = true
theme = "auto"
title-hidden = true
vsync = false
wsl = false

[font]
normal = ["Iosevka Nerd Font"] # Will use the bundled Fira Code Nerd Font by default
size = 20.0
